version: "3.8"
services:
  linux:
    container_name: linux
    volumes:
      - ./levels:/levels
      - ./workspace:/workspace
    working_dir: /levels
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
